# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4942df737f4aacaeb9cb5630c8013a53e5907baa30dac055c6fa119759f0aa2542a2e207aacbe7a59548f7a24b9cc8f6df73e429190419e05f0f8f5f507715c3

test:
  secret_key_base: 4d99303ecc1a0b9faa0a1152cbad1599ddbb726fcea8be6499fdc43e0c830363063d4333c676c628785d67c36a5722c8592d1791cd943c1eaecad1b744a3a7b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
